<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MediaVacuum.Core\MediaVacuum.Core.csproj" />
    <ProjectReference Include="..\MediaVacuum.Installer\MediaVacuum.Installer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Translations\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <!-- <ApplicationIcon>Assets\icon.ico</ApplicationIcon> -->
    <Title>MediaVacuum</Title>
    <Description>Interface graphique pour yt-dlp - Téléchargement de médias</Description>
    <Company>MediaVacuum</Company>
    <Product>MediaVacuum</Product>
    <Copyright>© 2024 MediaVacuum</Copyright>
    <AssemblyName>MediaVacuum</AssemblyName>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

</Project>
